name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.1
  - pip
  - ffmpeg
  - pip:
      - python-dotenv
      - requests
      - poetry
      - black
      - flake8
      - pre-commit
      - openai==1.76.2
      - langchain==0.3.24
      - langchain-core==0.3.56
      - langchain-text-splitters==0.3.8
      - langgraph==0.4.1
      - langgraph-checkpoint==2.0.25
      - langgraph-prebuilt==0.1.8
      - langgraph-sdk==0.1.66
      - langsmith==0.3.39
      - langserve==0.3.1
      - langgraph-cli==0.2.7
      - langchain-community==0.3.23
      - pydub==0.25.1
